layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  limit: 8
  exclude:
    archived: false
    forks: true
    projects:
      - CopyBundleID
      - rlenv

social_media:
  twitter: coord_e
  website: https://coordination.hatenablog.com/

topics:
  - name: Compiler
    web_url: https://github.com/topics/compiler

  - name: Programming language
    web_url: https://github.com/topics/programming-language

  - name: Type system
    web_url: https://github.com/topics/type-system

  - name: Formal theorem proving
    web_url: https://github.com/topics/theorem-proving

repository: coord-e/personal-website
